### ISSUE TITLE
promql queries return inconsistent data - log-cache 1.4.6

### ISSUE THREAD

**Issue by joerodriguez** [cloudfoundry/log-cache#93] opened 2018-09-25 17:29 UTC
promql queries return inconsistent data. A deployment was not active during this time. This is a black box cli health check which emits 0 or 1.

bash log:
[log-cache-1-4-6-inconsistent-data.txt](https://github.com/cloudfoundry/log-cache/files/2416340/log-cache-1-4-6-inconsistent-data.txt)

**Comment by toddboom** [comment] 2018-10-09 21:01
Thanks for reporting this, @joerodriguez! The issue is fixed in master.

**Closed as completed by toddboom** 2018-10-09 21:01 UTC
Labels: accepted
