### ISSUE TITLE
Maximum memory limit not applied unless minimum entries are present

### ISSUE THREAD

**Issue by aeijdenberg** [cloudfoundry/log-cache#88] opened 2018-09-07 05:56 UTC
We've noticed that with the default config that log-cache is using more than 50% of memory. I suspect it's because the memory based pruning does not kick in until after the minimum row count is checked:
https://github.com/cloudfoundry/log-cache/blob/master/internal/store/store.go#L213

Unsure if this is intentional or not. My expectation is that the maximum memory limit is a bigger hammer and should override a desired minimum number of rows?

**Comment by toddboom** [comment] 2018-09-07 22:04
@aeijdenberg Your "bigger hammer" suggestion is correct - this is happening by design. Are you running into a situation where the minimum store size is too high? We could probably just make it configurable via manifest if it seems useful.

**Comment by aeijdenberg** [comment] 2018-09-10 01:36
@toddboom - can you clarify whether the design is that a the max mem limit should override the min row count or vice versa? (and is this design documented outside of the code that itself?)

As an operator, I'd rather set the max mem limit and not even need to think about how many rows that is... (ie my goal is to stop our monitoring from alerting for more than 90% usage - we don't think we care how many rows are actually cached). If we need to also think about how many rows that is, then I need to start getting the calculator out and understanding size per row etc etc.

(our team should also reconsider using t2.micros for our dopplers... but I don't think that detracts from the substance of this issue)

**Comment by aeijdenberg** [comment] 2018-09-20 01:06
@toddboom - any thoughts on the above?

We're still regularly tripping our 90% threshold on our doppler VMs and would rather not have to do mathematics with each new release of Go and/or log-cache to re-calculate the right minimum number of rows to set to match the memory % target.

**Comment by jtuchscherer** [comment] 2018-09-26 22:33
@aeijdenberg We are going to remove the minimum row count soon.

And yes, t2.micros are very small for dopplers. You might consider using an ops file to not colocate log-cache and doppler anymore.

**Comment by paolostivanin** [comment] 2018-09-27 06:04
we are using `c4.xlarge` for our dopplers, and `log-cache` is also using >75% of memory on almost all (`30`) of them.

**Comment by toddboom** [comment] 2018-09-29 03:13
@paolostivanin What version of log-cache are you running?

**Comment by paolostivanin** [comment] 2018-10-02 12:00
@toddboom we are using 1.4.3

**Comment by toddboom** [comment] 2019-01-15 19:12
This is now fixed and was included in the v2.0.2 release:
https://github.com/cloudfoundry/log-cache-release/releases/tag/v2.0.2

**Closed as completed by toddboom** 2019-01-15 19:12 UTC
