### ISSUE TITLE
Specific metrics do not appear to be stored

### ISSUE THREAD

**Issue by joerodriguez** [cloudfoundry/log-cache#78] opened 2018-08-02 21:56 UTC
We are working on a validation tool for teams to use that ensures metric are being emitted properly. Most metrics for our source can be found in the read endpoint, but `health.check.cliCommand.probe.count` does not appear in v1.4.1. It does appear in the firehose. The value of this metric is `0` in our specific environment which may be related.

In the screen shot we are using `cf tail` on the left and `cf nozzle` on the right.
![screen shot 2018-08-02 at 3 52 13 pm](https://user-images.githubusercontent.com/74051/43613425-862d8c78-966c-11e8-9a72-9c1b673548d8.png)

**Comment by colins** [comment] 2018-08-07 21:33
@joerodriguez could you confirm that you're using the latest version of the CLI

**Comment by joerodriguez** [comment] 2018-08-08 15:35
We are using the newest version. Additionally we checked the /read and /promql endpoints directly.

**Comment by toddboom** [comment] 2018-08-22 22:12
@joerodriguez We were assuming that this had something to do with zero-value metrics, but we were still able to see zeroes coming through in our testing. Are you free for some XTP so that we can observe this in your environment and try to figure out where the issue is originating?

/cc @pianohacker

**Comment by bradylove** [comment] 2018-08-23 02:37
@toddboom @colins we ran into a similar issue on Loggregator with gauge metrics on the RLP Gateway. The RLP Gateway is not using the `grpc-gateway` however was converting protobuf envelopes to JSON with `jsonpb` which omits zero values default.

If you are able to set the marshaler for the `grpc-gateway` you should be able to turn on `EmitDefaults` which will emit the zero values. You can reference our fix for the RLP Gateway [here](https://github.com/cloudfoundry/loggregator/commit/af00466284f7c6fe854abde4e100d2f04195a9b9).

**Comment by toddboom** [comment] 2018-08-23 15:26
@bradylove thanks for the tip. i thought we had already done this here a while ago:

https://github.com/cloudfoundry/log-cache/commit/df05c6457305c8b633f00cc9e4a8cbfa89e2cf03

but i will take a look and see if it's happening somewhere else that we missed.

**Comment by toddboom** [comment] 2018-09-05 21:38
This is fixed in master.

**Closed as completed by toddboom** 2018-09-05 21:38 UTC
