### ISSUE TITLE
error: sample value must be a quoted string

### ISSUE THREAD

**Issue by dtimm** [cloudfoundry/log-cache#86] opened 2018-09-05 18:07 UTC
log-cache version 1.4.4

When I query the `/api/v1/query` endpoint, I would like the response to be consumable by tools targeting Prometheus. Currently, a Prometheus query endpoint returns `[[1536163500, "0"], [1536163530, "0"], [1536163560, "0"]...]`, but the log-cache query endpoint returns `[[1536163500, 0], [1536163530, 0], [1536163560, 0]...]`. Prometheus tooling expects the values to be in quoted string format.

**Comment by toddboom** [comment] 2018-09-05 21:34
@dtimm thanks for reporting this! we were actually just in the middle of rewriting this portion of the promql integration and it is now fixed in master. it will be available in the 1.4.5 release.

**Comment by toddboom** [comment] 2018-09-07 22:17
@dtimm Thanks for reporting this! The issue is fixed in master.

**Closed as completed by toddboom** 2018-09-07 22:17 UTC
